### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  id: WithOSDiskSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching(CachingTypes)
  - com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings(DiskEncryptionSettings)
  - com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName(String)
  - com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(int)
  - com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(Integer)
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: VirtualMachine.DefinitionStages.WithOSDiskSettings
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1121
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage of a virtual machine definition allowing to specify OS disk configurations. </p>"
  syntax:
    content: public interface WithOSDiskSettings
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching(CachingTypes)
  id: withOSDiskCaching(CachingTypes)
  parent: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: withOSDiskCaching(CachingTypes cachingType)
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching(CachingTypes cachingType)
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching(CachingTypes cachingType)
  overload: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1128
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the caching type for the OS disk.</p>\r\n<p></p>"
  syntax:
    content: public WithCreate withOSDiskCaching(CachingTypes cachingType)
    parameters:
    - id: cachingType
      type: com.microsoft.azure.management.compute.CachingTypes
      description: <p>a caching type </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings(DiskEncryptionSettings)
  id: withOSDiskEncryptionSettings(DiskEncryptionSettings)
  parent: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: withOSDiskEncryptionSettings(DiskEncryptionSettings settings)
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings(DiskEncryptionSettings settings)
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings(DiskEncryptionSettings settings)
  overload: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1136
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the encryption settings for the OS Disk.</p>\r\n<p></p>"
  syntax:
    content: public WithCreate withOSDiskEncryptionSettings(DiskEncryptionSettings settings)
    parameters:
    - id: settings
      type: com.microsoft.azure.management.compute.DiskEncryptionSettings
      description: <p>the encryption settings </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName(String)
  id: withOSDiskName(String)
  parent: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: withOSDiskName(String name)
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName(String name)
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName(String name)
  overload: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1161
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the name for the OS Disk.</p>\r\n<p></p>"
  syntax:
    content: public WithCreate withOSDiskName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>an OS disk name </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(int)
  id: withOSDiskSizeInGB(int)
  parent: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: withOSDiskSizeInGB(int size)
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(int size)
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(int size)
  overload: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1153
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the size of the OSDisk in GB.</p>\r\n<p></p>"
  syntax:
    content: public WithCreate withOSDiskSizeInGB(int size)
    parameters:
    - id: size
      type: f75371fa
      description: <p>the VHD size </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(Integer)
  id: withOSDiskSizeInGB(Integer)
  parent: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.yml
  langs:
  - java
  name: withOSDiskSizeInGB(Integer size)
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(Integer size)
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB(Integer size)
  overload: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java
    startLine: 1144
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the size of the OSDisk in GB.</p>\r\n<p></p>"
  syntax:
    content: public WithCreate withOSDiskSizeInGB(Integer size)
    parameters:
    - id: size
      type: 08effaa0
      description: <p>the VHD size </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
      description: <p>the next stage of the definition </p>
references:
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching*
  name: withOSDiskCaching
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskCaching
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings*
  name: withOSDiskEncryptionSettings
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskEncryptionSettings
  package: com.microsoft.azure.management.compute
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB*
  name: withOSDiskSizeInGB
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskSizeInGB
  package: com.microsoft.azure.management.compute
- uid: f75371fa
  spec.java:
  - name: int
    fullName: int
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName*
  name: withOSDiskName
  nameWithType: VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithOSDiskSettings.withOSDiskName
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate.yml
  name: VirtualMachine.DefinitionStages.WithCreate
  nameWithType: VirtualMachine.DefinitionStages.WithCreate
  fullName: com.microsoft.azure.management.compute.VirtualMachine.DefinitionStages.WithCreate
  type: Interface
  summary: "<p>The stage of the definition which contains all the minimum required inputs for the resource to be created, but also allows for any other optional settings to be specified. </p>"
  syntax:
    content: public interface WithCreate extends Creatable<VirtualMachine>,Resource.DefinitionWithTags<WithCreate>,VirtualMachine.DefinitionStages.WithOSDiskSettings,VirtualMachine.DefinitionStages.WithVMSize,VirtualMachine.DefinitionStages.WithStorageAccount,VirtualMachine.DefinitionStages.WithAvailabilitySet,VirtualMachine.DefinitionStages.WithSecondaryNetworkInterface,VirtualMachine.DefinitionStages.WithExtension,VirtualMachine.DefinitionStages.WithPlan,VirtualMachine.DefinitionStages.WithBootDiagnostics,VirtualMachine.DefinitionStages.WithManagedServiceIdentity
- uid: com.microsoft.azure.management.compute.CachingTypes
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.CachingTypes.yml
  name: CachingTypes
  nameWithType: CachingTypes
  fullName: com.microsoft.azure.management.compute.CachingTypes
  type: Enum
  summary: "<p>Defines values for CachingTypes. </p>"
  syntax:
    content: public enum CachingTypes
- uid: com.microsoft.azure.management.compute.DiskEncryptionSettings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.DiskEncryptionSettings.yml
  name: DiskEncryptionSettings
  nameWithType: DiskEncryptionSettings
  fullName: com.microsoft.azure.management.compute.DiskEncryptionSettings
  type: Class
  summary: "<p>Describes a Encryption Settings for a Disk. </p>"
  syntax:
    content: public class DiskEncryptionSettings
