### YamlMime:ManagedReference
items:
- uid: com.microsoft.applicationinsights.extensibility.context
  id: context
  children:
  - com.microsoft.applicationinsights.extensibility.context.CloudContext
  - com.microsoft.applicationinsights.extensibility.context.ComponentContext
  - com.microsoft.applicationinsights.extensibility.context.ContextTagKeys
  - com.microsoft.applicationinsights.extensibility.context.DeviceContext
  - com.microsoft.applicationinsights.extensibility.context.InternalContext
  - com.microsoft.applicationinsights.extensibility.context.LocationContext
  - com.microsoft.applicationinsights.extensibility.context.OperationContext
  - com.microsoft.applicationinsights.extensibility.context.SessionContext
  - com.microsoft.applicationinsights.extensibility.context.UserContext
  href: com.microsoft.applicationinsights.extensibility.context.yml
  langs:
  - java
  name: com.microsoft.applicationinsights.extensibility.context
  nameWithType: com.microsoft.applicationinsights.extensibility.context
  fullName: com.microsoft.applicationinsights.extensibility.context
  type: Namespace
  source:
    remote:
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/CloudContext.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/context/CloudContext.java
  syntax:
    content: package com.microsoft.applicationinsights.extensibility.context
references:
- uid: com.microsoft.applicationinsights.extensibility.context.CloudContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.CloudContext.yml
  name: CloudContext
  nameWithType: CloudContext
  fullName: com.microsoft.applicationinsights.extensibility.context.CloudContext
  type: Class
  syntax:
    content: public class CloudContext
- uid: com.microsoft.applicationinsights.extensibility.context.ComponentContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.ComponentContext.yml
  name: ComponentContext
  nameWithType: ComponentContext
  fullName: com.microsoft.applicationinsights.extensibility.context.ComponentContext
  type: Class
  syntax:
    content: public class ComponentContext
- uid: com.microsoft.applicationinsights.extensibility.context.ContextTagKeys
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.ContextTagKeys.yml
  name: ContextTagKeys
  nameWithType: ContextTagKeys
  fullName: com.microsoft.applicationinsights.extensibility.context.ContextTagKeys
  type: Class
  summary: "<p>ContextTagKeys </p>"
  syntax:
    content: public class ContextTagKeys
- uid: com.microsoft.applicationinsights.extensibility.context.DeviceContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.DeviceContext.yml
  name: DeviceContext
  nameWithType: DeviceContext
  fullName: com.microsoft.applicationinsights.extensibility.context.DeviceContext
  type: Class
  syntax:
    content: public class DeviceContext
- uid: com.microsoft.applicationinsights.extensibility.context.InternalContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.InternalContext.yml
  name: InternalContext
  nameWithType: InternalContext
  fullName: com.microsoft.applicationinsights.extensibility.context.InternalContext
  type: Class
  syntax:
    content: public class InternalContext
- uid: com.microsoft.applicationinsights.extensibility.context.LocationContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.LocationContext.yml
  name: LocationContext
  nameWithType: LocationContext
  fullName: com.microsoft.applicationinsights.extensibility.context.LocationContext
  type: Class
  syntax:
    content: public class LocationContext
- uid: com.microsoft.applicationinsights.extensibility.context.OperationContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.OperationContext.yml
  name: OperationContext
  nameWithType: OperationContext
  fullName: com.microsoft.applicationinsights.extensibility.context.OperationContext
  type: Class
  syntax:
    content: public class OperationContext
- uid: com.microsoft.applicationinsights.extensibility.context.SessionContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.SessionContext.yml
  name: SessionContext
  nameWithType: SessionContext
  fullName: com.microsoft.applicationinsights.extensibility.context.SessionContext
  type: Class
  syntax:
    content: public class SessionContext
- uid: com.microsoft.applicationinsights.extensibility.context.UserContext
  parent: com.microsoft.applicationinsights.extensibility.context
  href: com.microsoft.applicationinsights.extensibility.context.UserContext.yml
  name: UserContext
  nameWithType: UserContext
  fullName: com.microsoft.applicationinsights.extensibility.context.UserContext
  type: Class
  syntax:
    content: public class UserContext
