### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.SshConfiguration
  id: SshConfiguration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.SshConfiguration.publicKeys()
  - com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys(List<SshPublicKey>)
  href: com.microsoft.azure.management.compute.SshConfiguration.yml
  langs:
  - java
  name: SshConfiguration
  nameWithType: SshConfiguration
  fullName: com.microsoft.azure.management.compute.SshConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 16
  package: com.microsoft.azure.management.compute
  summary: "<p>SSH configuration for Linux based VMs running on Azure. </p>"
  syntax: &o1
    content: public class SshConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.SshConfiguration.publicKeys()
  id: publicKeys()
  parent: com.microsoft.azure.management.compute.SshConfiguration
  href: com.microsoft.azure.management.compute.SshConfiguration.yml
  langs:
  - java
  name: publicKeys()
  nameWithType: SshConfiguration.publicKeys()
  fullName: com.microsoft.azure.management.compute.SshConfiguration.publicKeys()
  overload: com.microsoft.azure.management.compute.SshConfiguration.publicKeys*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 28
  package: com.microsoft.azure.management.compute
  summary: "<p>Get the publicKeys value.</p>\r\n<p></p>"
  syntax:
    content: public List<SshPublicKey> publicKeys()
    return:
      type: 5618da2dcom.microsoft.azure.management.compute.SshPublicKeya08ddfce
      description: <p>the publicKeys value </p>
- uid: com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys(List<SshPublicKey>)
  id: withPublicKeys(List<SshPublicKey>)
  parent: com.microsoft.azure.management.compute.SshConfiguration
  href: com.microsoft.azure.management.compute.SshConfiguration.yml
  langs:
  - java
  name: withPublicKeys(List<SshPublicKey> publicKeys)
  nameWithType: SshConfiguration.withPublicKeys(List<SshPublicKey> publicKeys)
  fullName: com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys(List<SshPublicKey> publicKeys)
  overload: com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/SshConfiguration.java
    startLine: 38
  package: com.microsoft.azure.management.compute
  summary: "<p>Set the publicKeys value.</p>\r\n<p></p>"
  syntax:
    content: public SshConfiguration withPublicKeys(List<SshPublicKey> publicKeys)
    parameters:
    - id: publicKeys
      type: 5618da2dcom.microsoft.azure.management.compute.SshPublicKeya08ddfce
      description: <p>the publicKeys value to set </p>
    return:
      type: com.microsoft.azure.management.compute.SshConfiguration
      description: <p>the SshConfiguration object itself. </p>
references:
- uid: 5618da2dcom.microsoft.azure.management.compute.SshPublicKeya08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.compute.SshPublicKey
    name: SshPublicKey
    fullName: com.microsoft.azure.management.compute.SshPublicKey
    href: com.microsoft.azure.management.compute.SshPublicKey.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.compute.SshConfiguration.publicKeys*
  name: publicKeys
  nameWithType: SshConfiguration.publicKeys
  fullName: com.microsoft.azure.management.compute.SshConfiguration.publicKeys
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys*
  name: withPublicKeys
  nameWithType: SshConfiguration.withPublicKeys
  fullName: com.microsoft.azure.management.compute.SshConfiguration.withPublicKeys
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.SshPublicKey
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.SshPublicKey.yml
  name: SshPublicKey
  nameWithType: SshPublicKey
  fullName: com.microsoft.azure.management.compute.SshPublicKey
  type: Class
  summary: "<p>Contains information about SSH certificate public key and the path on the Linux VM where the public key is placed. </p>"
  syntax:
    content: public class SshPublicKey
- uid: com.microsoft.azure.management.compute.SshConfiguration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.SshConfiguration.yml
  name: SshConfiguration
  nameWithType: SshConfiguration
  fullName: com.microsoft.azure.management.compute.SshConfiguration
  type: Class
  summary: "<p>SSH configuration for Linux based VMs running on Azure. </p>"
  syntax: *o1
