### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  id: AzureBlobStorageApplicationLogsConfig
  parent: com.microsoft.azure.management.appservice
  children:
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level()
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays()
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl()
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel(LogLevel)
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays(Integer)
  - com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl(String)
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: AzureBlobStorageApplicationLogsConfig
  nameWithType: AzureBlobStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 15
  package: com.microsoft.azure.management.appservice
  summary: "<p>Application logs azure blob storage configuration. </p>"
  syntax: &o1
    content: public class AzureBlobStorageApplicationLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level()
  id: level()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: level()
  nameWithType: AzureBlobStorageApplicationLogsConfig.level()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 43
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the level value.</p>\r\n<p></p>"
  syntax:
    content: public LogLevel level()
    return:
      type: com.microsoft.azure.management.appservice.LogLevel
      description: <p>the level value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays()
  id: retentionInDays()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: retentionInDays()
  nameWithType: AzureBlobStorageApplicationLogsConfig.retentionInDays()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 83
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl()
  id: sasUrl()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: sasUrl()
  nameWithType: AzureBlobStorageApplicationLogsConfig.sasUrl()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 63
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the sasUrl value.</p>\r\n<p></p>"
  syntax:
    content: public String sasUrl()
    return:
      type: "26831127"
      description: <p>the sasUrl value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel(LogLevel)
  id: withLevel(LogLevel)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: withLevel(LogLevel level)
  nameWithType: AzureBlobStorageApplicationLogsConfig.withLevel(LogLevel level)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel(LogLevel level)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 53
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the level value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withLevel(LogLevel level)
    parameters:
    - id: level
      type: com.microsoft.azure.management.appservice.LogLevel
      description: <p>the level value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
      description: <p>the AzureBlobStorageApplicationLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays(Integer)
  id: withRetentionInDays(Integer)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  nameWithType: AzureBlobStorageApplicationLogsConfig.withRetentionInDays(Integer retentionInDays)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays(Integer retentionInDays)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 93
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
      description: <p>the AzureBlobStorageApplicationLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl(String)
  id: withSasUrl(String)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  langs:
  - java
  name: withSasUrl(String sasUrl)
  nameWithType: AzureBlobStorageApplicationLogsConfig.withSasUrl(String sasUrl)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl(String sasUrl)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageApplicationLogsConfig.java
    startLine: 73
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the sasUrl value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageApplicationLogsConfig withSasUrl(String sasUrl)
    parameters:
    - id: sasUrl
      type: "26831127"
      description: <p>the sasUrl value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
      description: <p>the AzureBlobStorageApplicationLogsConfig object itself. </p>
references:
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level*
  name: level
  nameWithType: AzureBlobStorageApplicationLogsConfig.level
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.level
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel*
  name: withLevel
  nameWithType: AzureBlobStorageApplicationLogsConfig.withLevel
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withLevel
  package: com.microsoft.azure.management.appservice
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl*
  name: sasUrl
  nameWithType: AzureBlobStorageApplicationLogsConfig.sasUrl
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.sasUrl
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl*
  name: withSasUrl
  nameWithType: AzureBlobStorageApplicationLogsConfig.withSasUrl
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withSasUrl
  package: com.microsoft.azure.management.appservice
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays*
  name: retentionInDays
  nameWithType: AzureBlobStorageApplicationLogsConfig.retentionInDays
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.retentionInDays
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays*
  name: withRetentionInDays
  nameWithType: AzureBlobStorageApplicationLogsConfig.withRetentionInDays
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.withRetentionInDays
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.LogLevel
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.LogLevel.yml
  name: LogLevel
  nameWithType: LogLevel
  fullName: com.microsoft.azure.management.appservice.LogLevel
  type: Enum
  summary: "<p>Defines values for LogLevel. </p>"
  syntax:
    content: public enum LogLevel
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig.yml
  name: AzureBlobStorageApplicationLogsConfig
  nameWithType: AzureBlobStorageApplicationLogsConfig
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageApplicationLogsConfig
  type: Class
  summary: "<p>Application logs azure blob storage configuration. </p>"
  syntax: *o1
