### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  id: FileSystemHttpLogsConfig
  parent: com.microsoft.azure.management.appservice
  children:
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled()
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays()
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb()
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled(Boolean)
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays(Integer)
  - com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb(Integer)
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: FileSystemHttpLogsConfig
  nameWithType: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 15
  package: com.microsoft.azure.management.appservice
  summary: "<p>Http logs to file system configuration. </p>"
  syntax: &o1
    content: public class FileSystemHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled()
  id: enabled()
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: enabled()
  nameWithType: FileSystemHttpLogsConfig.enabled()
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled()
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 83
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the enabled value.</p>\r\n<p></p>"
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays()
  id: retentionInDays()
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: retentionInDays()
  nameWithType: FileSystemHttpLogsConfig.retentionInDays()
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays()
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 63
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb()
  id: retentionInMb()
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: retentionInMb()
  nameWithType: FileSystemHttpLogsConfig.retentionInMb()
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb()
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 43
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the retentionInMb value.</p>\r\n<p></p>"
  syntax:
    content: public Integer retentionInMb()
    return:
      type: 08effaa0
      description: <p>the retentionInMb value </p>
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled(Boolean)
  id: withEnabled(Boolean)
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  nameWithType: FileSystemHttpLogsConfig.withEnabled(Boolean enabled)
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled(Boolean enabled)
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 93
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the enabled value.</p>\r\n<p></p>"
  syntax:
    content: public FileSystemHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
      description: <p>the FileSystemHttpLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays(Integer)
  id: withRetentionInDays(Integer)
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  nameWithType: FileSystemHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 73
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
      description: <p>the FileSystemHttpLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb(Integer)
  id: withRetentionInMb(Integer)
  parent: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  langs:
  - java
  name: withRetentionInMb(Integer retentionInMb)
  nameWithType: FileSystemHttpLogsConfig.withRetentionInMb(Integer retentionInMb)
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb(Integer retentionInMb)
  overload: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemHttpLogsConfig.java
    startLine: 53
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the retentionInMb value.</p>\r\n<p></p>"
  syntax:
    content: public FileSystemHttpLogsConfig withRetentionInMb(Integer retentionInMb)
    parameters:
    - id: retentionInMb
      type: 08effaa0
      description: <p>the retentionInMb value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
      description: <p>the FileSystemHttpLogsConfig object itself. </p>
references:
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb*
  name: retentionInMb
  nameWithType: FileSystemHttpLogsConfig.retentionInMb
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInMb
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb*
  name: withRetentionInMb
  nameWithType: FileSystemHttpLogsConfig.withRetentionInMb
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInMb
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays*
  name: retentionInDays
  nameWithType: FileSystemHttpLogsConfig.retentionInDays
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.retentionInDays
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays*
  name: withRetentionInDays
  nameWithType: FileSystemHttpLogsConfig.withRetentionInDays
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withRetentionInDays
  package: com.microsoft.azure.management.appservice
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled*
  name: enabled
  nameWithType: FileSystemHttpLogsConfig.enabled
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.enabled
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled*
  name: withEnabled
  nameWithType: FileSystemHttpLogsConfig.withEnabled
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.withEnabled
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig.yml
  name: FileSystemHttpLogsConfig
  nameWithType: FileSystemHttpLogsConfig
  fullName: com.microsoft.azure.management.appservice.FileSystemHttpLogsConfig
  type: Class
  summary: "<p>Http logs to file system configuration. </p>"
  syntax: *o1
