### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  id: VirtualMachineScaleSetPublicIPAddressConfiguration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings()
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes()
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name()
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes(Integer)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName(String)
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: VirtualMachineScaleSetPublicIPAddressConfiguration
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 18
  package: com.microsoft.azure.management.compute
  summary: "<p>Describes a virtual machines scale set IP Configuration's PublicIPAddress configuration. </p>"
  syntax: &o1
    content: public class VirtualMachineScaleSetPublicIPAddressConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings()
  id: dnsSettings()
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: dnsSettings()
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings()
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings()
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 82
  package: com.microsoft.azure.management.compute
  summary: "<p>Get the dnsSettings value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings dnsSettings()
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
      description: <p>the dnsSettings value </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes()
  id: idleTimeoutInMinutes()
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: idleTimeoutInMinutes()
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes()
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes()
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 62
  package: com.microsoft.azure.management.compute
  summary: "<p>Get the idleTimeoutInMinutes value.</p>\r\n<p></p>"
  syntax:
    content: public Integer idleTimeoutInMinutes()
    return:
      type: 08effaa0
      description: <p>the idleTimeoutInMinutes value </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name()
  id: name()
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: name()
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.name()
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name()
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 42
  package: com.microsoft.azure.management.compute
  summary: "<p>Get the name value.</p>\r\n<p></p>"
  syntax:
    content: public String name()
    return:
      type: "26831127"
      description: <p>the name value </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings)
  id: withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings dnsSettings)
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings dnsSettings)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings dnsSettings)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 92
  package: com.microsoft.azure.management.compute
  summary: "<p>Set the dnsSettings value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualMachineScaleSetPublicIPAddressConfiguration withDnsSettings(VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings dnsSettings)
    parameters:
    - id: dnsSettings
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
      description: <p>the dnsSettings value to set </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
      description: <p>the VirtualMachineScaleSetPublicIPAddressConfiguration object itself. </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes(Integer)
  id: withIdleTimeoutInMinutes(Integer)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: withIdleTimeoutInMinutes(Integer idleTimeoutInMinutes)
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes(Integer idleTimeoutInMinutes)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes(Integer idleTimeoutInMinutes)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 72
  package: com.microsoft.azure.management.compute
  summary: "<p>Set the idleTimeoutInMinutes value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualMachineScaleSetPublicIPAddressConfiguration withIdleTimeoutInMinutes(Integer idleTimeoutInMinutes)
    parameters:
    - id: idleTimeoutInMinutes
      type: 08effaa0
      description: <p>the idleTimeoutInMinutes value to set </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
      description: <p>the VirtualMachineScaleSetPublicIPAddressConfiguration object itself. </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName(String)
  id: withName(String)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  langs:
  - java
  name: withName(String name)
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withName(String name)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName(String name)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetPublicIPAddressConfiguration.java
    startLine: 52
  package: com.microsoft.azure.management.compute
  summary: "<p>Set the name value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualMachineScaleSetPublicIPAddressConfiguration withName(String name)
    parameters:
    - id: name
      type: "26831127"
      description: <p>the name value to set </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
      description: <p>the VirtualMachineScaleSetPublicIPAddressConfiguration object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name*
  name: name
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.name
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.name
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName*
  name: withName
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withName
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withName
  package: com.microsoft.azure.management.compute
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes*
  name: idleTimeoutInMinutes
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.idleTimeoutInMinutes
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes*
  name: withIdleTimeoutInMinutes
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withIdleTimeoutInMinutes
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings*
  name: dnsSettings
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.dnsSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings*
  name: withDnsSettings
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.withDnsSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings.yml
  name: VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
  type: Class
  summary: "<p>Describes a virtual machines scale sets network configuration's DNS settings. </p>"
  syntax:
    content: public class VirtualMachineScaleSetPublicIPAddressConfigurationDnsSettings
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration.yml
  name: VirtualMachineScaleSetPublicIPAddressConfiguration
  nameWithType: VirtualMachineScaleSetPublicIPAddressConfiguration
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetPublicIPAddressConfiguration
  type: Class
  summary: "<p>Describes a virtual machines scale set IP Configuration's PublicIPAddress configuration. </p>"
  syntax: *o1
