### YamlMime:ManagedReference
items:
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  id: PronunciationAssessmentConfig
  parent: com.microsoft.cognitiveservices.speech
  children:
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo(Recognizer)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close()
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson(String)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText()
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity,boolean)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText(String)
  - com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson()
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: PronunciationAssessmentConfig
  nameWithType: PronunciationAssessmentConfig
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  type: Class
  source:
    remote: &o0
      path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
      branch: javadocs201809
      repo: https://msasg.visualstudio.com/DefaultCollection/Skyman/_git/Carbon
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 22
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Represents pronunciation assessment configuration Added in version 1.14.0 </p>"
  syntax: &o1
    content: public class PronunciationAssessmentConfig
  inheritance:
  - java.lang.Object
  - Closeable
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo(Recognizer)
  id: applyTo(Recognizer)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: applyTo(Recognizer recognizer)
  nameWithType: PronunciationAssessmentConfig.applyTo(Recognizer recognizer)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo(Recognizer recognizer)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 133
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Applies the settings in this config to a recognizer. </p>"
  syntax:
    content: public void applyTo(Recognizer recognizer)
    parameters:
    - id: recognizer
      type: com.microsoft.cognitiveservices.speech.Recognizer
      description: <p>The target recognizer. </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close()
  id: close()
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: close()
  nameWithType: PronunciationAssessmentConfig.close()
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close()
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 87
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Explicitly frees any external resource attached to the object </p>"
  syntax:
    content: public void close()
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson(String)
  id: fromJson(String)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: fromJson(String json)
  nameWithType: PronunciationAssessmentConfig.fromJson(String json)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson(String json)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 77
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Creates an instance of the PronunciationAssessmentConfig from a json string </p>"
  syntax:
    content: public static PronunciationAssessmentConfig fromJson(String json)
    parameters:
    - id: json
      type: "26831127"
      description: <p>the json string </p>
    return:
      type: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
      description: <p>The pronunciation assessment configuration being created. </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText()
  id: getReferenceText()
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: getReferenceText()
  nameWithType: PronunciationAssessmentConfig.getReferenceText()
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText()
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 116
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Gets the reference text. </p>"
  syntax:
    content: public String getReferenceText()
    return:
      type: "26831127"
      description: <p>The reference text. </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String)
  id: PronunciationAssessmentConfig(String)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: PronunciationAssessmentConfig(String referenceText)
  nameWithType: PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig*
  type: Constructor
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 68
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Initializes an instance of the PronunciationAssessmentConfig For the parameters details, see <a href=\"https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters\">https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters</a></p>"
  syntax:
    content: public PronunciationAssessmentConfig(String referenceText)
    parameters:
    - id: referenceText
      type: "26831127"
      description: <p>The reference text </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity)
  id: PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity)
  nameWithType: PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig*
  type: Constructor
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 58
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Initializes an instance of the PronunciationAssessmentConfig For the parameters details, see <a href=\"https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters\">https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters</a></p>"
  syntax:
    content: public PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity)
    parameters:
    - id: referenceText
      type: "26831127"
      description: <p>The reference text </p>
    - id: gradingSystem
      type: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGradingSystem
      description: <p>The point system for score calibration </p>
    - id: granularity
      type: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGranularity
      description: <p>The evaluation granularity </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity,boolean)
  id: PronunciationAssessmentConfig(String,PronunciationAssessmentGradingSystem,PronunciationAssessmentGranularity,boolean)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity, boolean enableMiscue)
  nameWithType: PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity, boolean enableMiscue)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity, boolean enableMiscue)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig*
  type: Constructor
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 44
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Initializes an instance of the PronunciationAssessmentConfig For the parameters details, see <a href=\"https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters\">https://docs.microsoft.com/azure/cognitive-services/speech-service/rest-speech-to-text#pronunciation-assessment-parameters</a></p>"
  syntax:
    content: public PronunciationAssessmentConfig(String referenceText, PronunciationAssessmentGradingSystem gradingSystem, PronunciationAssessmentGranularity granularity, boolean enableMiscue)
    parameters:
    - id: referenceText
      type: "26831127"
      description: <p>The reference text </p>
    - id: gradingSystem
      type: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGradingSystem
      description: <p>The point system for score calibration </p>
    - id: granularity
      type: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGranularity
      description: <p>The evaluation granularity </p>
    - id: enableMiscue
      type: 4fc6e284
      description: <p>If enables miscue calculation </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText(String)
  id: setReferenceText(String)
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: setReferenceText(String value)
  nameWithType: PronunciationAssessmentConfig.setReferenceText(String value)
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText(String value)
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 107
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Sets the reference text. </p>"
  syntax:
    content: public void setReferenceText(String value)
    parameters:
    - id: value
      type: "26831127"
      description: <p>the reference text. </p>
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson()
  id: toJson()
  parent: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  langs:
  - java
  name: toJson()
  nameWithType: PronunciationAssessmentConfig.toJson()
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson()
  overload: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/PronunciationAssessmentConfig.java
    startLine: 124
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Gets the json string of pronunciation assessment parameters. </p>"
  syntax:
    content: public String toJson()
    return:
      type: "26831127"
      description: <p>json string of pronunciation assessment parameters. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig*
  name: PronunciationAssessmentConfig
  nameWithType: PronunciationAssessmentConfig.PronunciationAssessmentConfig
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.PronunciationAssessmentConfig
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close*
  name: close
  nameWithType: PronunciationAssessmentConfig.close
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.close
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText*
  name: setReferenceText
  nameWithType: PronunciationAssessmentConfig.setReferenceText
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.setReferenceText
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText*
  name: getReferenceText
  nameWithType: PronunciationAssessmentConfig.getReferenceText
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.getReferenceText
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson*
  name: toJson
  nameWithType: PronunciationAssessmentConfig.toJson
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.toJson
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo*
  name: applyTo
  nameWithType: PronunciationAssessmentConfig.applyTo
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.applyTo
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson*
  name: fromJson
  nameWithType: PronunciationAssessmentConfig.fromJson
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.fromJson
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.PropertyCollection
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.PropertyCollection.yml
  name: PropertyCollection
  nameWithType: PropertyCollection
  fullName: com.microsoft.cognitiveservices.speech.PropertyCollection
  type: Class
  summary: "<p>Represents collection of properties and their values. </p>"
  syntax:
    content: public class PropertyCollection
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGradingSystem
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGradingSystem.yml
  name: PronunciationAssessmentGradingSystem
  nameWithType: PronunciationAssessmentGradingSystem
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGradingSystem
  type: Enum
  summary: "<p>Defines the point system for pronunciation score calibration; default value is FivePoint. Added in version 1.14.0 </p>"
  syntax:
    content: public enum PronunciationAssessmentGradingSystem
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGranularity
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGranularity.yml
  name: PronunciationAssessmentGranularity
  nameWithType: PronunciationAssessmentGranularity
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentGranularity
  type: Enum
  summary: "<p>Defines the pronunciation evaluation granularity; default value is Phoneme. Added in version 1.14.0 </p>"
  syntax:
    content: public enum PronunciationAssessmentGranularity
- uid: com.microsoft.cognitiveservices.speech.Recognizer
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.Recognizer.yml
  name: Recognizer
  nameWithType: Recognizer
  fullName: com.microsoft.cognitiveservices.speech.Recognizer
  type: Class
  summary: "<p>Defines the base class Recognizer which mainly contains common event handlers. </p>"
  syntax:
    content: public class Recognizer
- uid: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig.yml
  name: PronunciationAssessmentConfig
  nameWithType: PronunciationAssessmentConfig
  fullName: com.microsoft.cognitiveservices.speech.PronunciationAssessmentConfig
  type: Class
  summary: "<p>Represents pronunciation assessment configuration Added in version 1.14.0 </p>"
  syntax: *o1
