### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  id: ContainerServiceSshConfiguration
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys()
  - com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys(List<ContainerServiceSshPublicKey>)
  href: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.yml
  langs:
  - java
  name: ContainerServiceSshConfiguration
  nameWithType: ContainerServiceSshConfiguration
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ContainerServiceSshConfiguration.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ContainerServiceSshConfiguration.java
    startLine: 16
  package: com.microsoft.azure.management.compute
  summary: "<p>SSH configuration for Linux-based VMs running on Azure. </p>"
  syntax: &o1
    content: public class ContainerServiceSshConfiguration
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys()
  id: publicKeys()
  parent: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  href: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.yml
  langs:
  - java
  name: publicKeys()
  nameWithType: ContainerServiceSshConfiguration.publicKeys()
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys()
  overload: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ContainerServiceSshConfiguration.java
    startLine: 28
  package: com.microsoft.azure.management.compute
  summary: "<p>Get the publicKeys value.</p>\r\n<p></p>"
  syntax:
    content: public List<ContainerServiceSshPublicKey> publicKeys()
    return:
      type: 5618da2dcom.microsoft.azure.management.compute.ContainerServiceSshPublicKeya08ddfce
      description: <p>the publicKeys value </p>
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys(List<ContainerServiceSshPublicKey>)
  id: withPublicKeys(List<ContainerServiceSshPublicKey>)
  parent: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  href: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.yml
  langs:
  - java
  name: withPublicKeys(List<ContainerServiceSshPublicKey> publicKeys)
  nameWithType: ContainerServiceSshConfiguration.withPublicKeys(List<ContainerServiceSshPublicKey> publicKeys)
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys(List<ContainerServiceSshPublicKey> publicKeys)
  overload: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/ContainerServiceSshConfiguration.java
    startLine: 38
  package: com.microsoft.azure.management.compute
  summary: "<p>Set the publicKeys value.</p>\r\n<p></p>"
  syntax:
    content: public ContainerServiceSshConfiguration withPublicKeys(List<ContainerServiceSshPublicKey> publicKeys)
    parameters:
    - id: publicKeys
      type: 5618da2dcom.microsoft.azure.management.compute.ContainerServiceSshPublicKeya08ddfce
      description: <p>the publicKeys value to set </p>
    return:
      type: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
      description: <p>the ContainerServiceSshConfiguration object itself. </p>
references:
- uid: 5618da2dcom.microsoft.azure.management.compute.ContainerServiceSshPublicKeya08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey
    name: ContainerServiceSshPublicKey
    fullName: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey
    href: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys*
  name: publicKeys
  nameWithType: ContainerServiceSshConfiguration.publicKeys
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.publicKeys
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys*
  name: withPublicKeys
  nameWithType: ContainerServiceSshConfiguration.withPublicKeys
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.withPublicKeys
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey.yml
  name: ContainerServiceSshPublicKey
  nameWithType: ContainerServiceSshPublicKey
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshPublicKey
  type: Class
  summary: "<p>Contains information about SSH certificate public key data. </p>"
  syntax:
    content: public class ContainerServiceSshPublicKey
- uid: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration.yml
  name: ContainerServiceSshConfiguration
  nameWithType: ContainerServiceSshConfiguration
  fullName: com.microsoft.azure.management.compute.ContainerServiceSshConfiguration
  type: Class
  summary: "<p>SSH configuration for Linux-based VMs running on Azure. </p>"
  syntax: *o1
