### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
  id: WithFromImageDiskSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withCaching(CachingTypes)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withSizeInGB(Integer)
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.yml
  langs:
  - java
  name: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 86
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage that allows configure the unmanaged disk based on an image.</p>\r\n<p></p>"
  syntax: &o1
    content: public interface WithFromImageDiskSettings<ParentT> extends VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.attach()
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withCaching(CachingTypes)
  id: withCaching(CachingTypes)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.yml
  langs:
  - java
  name: withCaching(CachingTypes cachingType)
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withCaching*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 101
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the caching type for the unmanaged data disk.</p>\r\n<p></p>"
  syntax:
    content: public WithFromImageDiskSettings<ParentT> withCaching(CachingTypes cachingType)
    parameters:
    - id: cachingType
      type: com.microsoft.azure.management.compute.CachingTypes
      description: "<p>the disk caching type. Possible values include: 'None', 'ReadOnly', 'ReadWrite' </p>"
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettingsda8a2936
      description: <p>the next stage of unmanaged data disk definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withSizeInGB(Integer)
  id: withSizeInGB(Integer)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.yml
  langs:
  - java
  name: withSizeInGB(Integer sizeInGB)
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withSizeInGB(Integer sizeInGB)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withSizeInGB(Integer sizeInGB)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withSizeInGB*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 93
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the size in GB the unmanaged disk needs to be resized.</p>\r\n<p></p>"
  syntax:
    content: public WithFromImageDiskSettings<ParentT> withSizeInGB(Integer sizeInGB)
    parameters:
    - id: sizeInGB
      type: 08effaa0
      description: <p>the disk size in GB </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettingsda8a2936
      description: <p>the next stage of unmanaged data disk definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettingsda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
    name: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
    fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
    href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withSizeInGB*
  name: withSizeInGB
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withSizeInGB
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withSizeInGB
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.withCaching*
  name: withCaching
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withCaching
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>.withCaching
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition
  href: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.yml
  name: attach()
  nameWithType: Attachable.InDefinition<ParentT>.attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: "<p>Attaches the child definition to the parent resource definiton. </p>"
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: "<p>The final stage of the unmanaged data disk definition.</p>\r\n<p></p>"
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionWithImage
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionWithImage.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionWithImage<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionWithImage<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionWithImage<ParentT>
  type: Interface
  summary: "<p>The entirety of a unmanaged data disk of a virtual machine scale set definition. </p>"
  syntax:
    content: public interface DefinitionWithImage<ParentT> extends VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.Blank<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithDiskSource<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.DefinitionStages.WithFromImageDiskSettings<ParentT>
  type: Interface
  summary: "<p>The stage that allows configure the unmanaged disk based on an image.</p>\r\n<p></p>"
  syntax: *o1
- uid: com.microsoft.azure.management.compute.CachingTypes
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.CachingTypes.yml
  name: CachingTypes
  nameWithType: CachingTypes
  fullName: com.microsoft.azure.management.compute.CachingTypes
  type: Enum
  summary: "<p>Defines values for CachingTypes. </p>"
  syntax:
    content: public enum CachingTypes
