### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  id: WithSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting(String,Object)
  - com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings(HashMap<String, Object>)
  - com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting(String,Object)
  - com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings(HashMap<String, Object>)
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.yml
  langs:
  - java
  name: VirtualMachineExtension.UpdateStages.WithSettings
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 435
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage of the virtual machine extension update allowing to add or update public and private settings. </p>"
  syntax:
    content: public interface WithSettings
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting(String,Object)
  id: withProtectedSetting(String,Object)
  parent: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.yml
  langs:
  - java
  name: withProtectedSetting(String key, Object value)
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting(String key, Object value)
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting(String key, Object value)
  overload: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 452
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies a private settings entry.</p>\r\n<p></p>"
  syntax:
    content: public Update withProtectedSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a private settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the private settings entry </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings(HashMap<String, Object>)
  id: withProtectedSettings(HashMap<String, Object>)
  parent: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.yml
  langs:
  - java
  name: withProtectedSettings(HashMap<String, Object> settings)
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings(HashMap<String, Object> settings)
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings(HashMap<String, Object> settings)
  overload: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 468
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies private settings.</p>\r\n<p></p>"
  syntax:
    content: public Update withProtectedSettings(HashMap<String, Object> settings)
    parameters:
    - id: settings
      type: f39c727f
      description: <p>the private settings </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting(String,Object)
  id: withPublicSetting(String,Object)
  parent: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.yml
  langs:
  - java
  name: withPublicSetting(String key, Object value)
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting(String key, Object value)
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting(String key, Object value)
  overload: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 443
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies a public settings entry.</p>\r\n<p></p>"
  syntax:
    content: public Update withPublicSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a public settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the public settings entry </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
      description: <p>the next stage of the update </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings(HashMap<String, Object>)
  id: withPublicSettings(HashMap<String, Object>)
  parent: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.yml
  langs:
  - java
  name: withPublicSettings(HashMap<String, Object> settings)
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings(HashMap<String, Object> settings)
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings(HashMap<String, Object> settings)
  overload: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineExtension.java
    startLine: 460
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies public settings.</p>\r\n<p></p>"
  syntax:
    content: public Update withPublicSettings(HashMap<String, Object> settings)
    parameters:
    - id: settings
      type: f39c727f
      description: <p>the public settings </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
      description: <p>the next stage of the update </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting*
  name: withPublicSetting
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSetting
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting*
  name: withProtectedSetting
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSetting
  package: com.microsoft.azure.management.compute
- uid: f39c727f
  spec.java:
  - name: HashMap<String, Object>
    fullName: HashMap<String, Object>
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings*
  name: withPublicSettings
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withPublicSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings*
  name: withProtectedSettings
  nameWithType: VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.UpdateStages.WithSettings.withProtectedSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineExtension.Update.yml
  name: VirtualMachineExtension.Update
  nameWithType: VirtualMachineExtension.Update
  fullName: com.microsoft.azure.management.compute.VirtualMachineExtension.Update
  type: Interface
  summary: "<p>The entirety of virtual machine extension update as a part of parent virtual machine update. </p>"
  syntax:
    content: public interface Update extends Settable<VirtualMachine.Update>,VirtualMachineExtension.UpdateStages.WithAutoUpgradeMinorVersion,VirtualMachineExtension.UpdateStages.WithSettings,VirtualMachineExtension.UpdateStages.WithTags
