### YamlMime:ManagedReference
items:
- uid: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer
  id: DeviceInfoContextInitializer
  parent: com.microsoft.applicationinsights.extensibility.initializer
  children:
  - com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize(TelemetryContext)
  href: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.yml
  langs:
  - java
  name: DeviceInfoContextInitializer
  nameWithType: DeviceInfoContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/DeviceInfoContextInitializer.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/DeviceInfoContextInitializer.java
    startLine: 32
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: "<p>Initializer class for device context information. </p>"
  syntax:
    content: public class DeviceInfoContextInitializer implements ContextInitializer
  inheritance:
  - java.lang.Object
  - com.microsoft.applicationinsights.extensibility.ContextInitializer
- uid: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize(TelemetryContext)
  id: initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer
  href: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.yml
  langs:
  - java
  name: initialize(TelemetryContext context)
  nameWithType: DeviceInfoContextInitializer.initialize(TelemetryContext context)
  fullName: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize(TelemetryContext context)
  overload: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize*
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/initializer/DeviceInfoContextInitializer.java
    startLine: 35
  package: com.microsoft.applicationinsights.extensibility.initializer
  summary: "<p>Initializes the given TelemetryContext. </p>"
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: f8422c74
      description: <p>A TelemetryContext to initialize. </p>
  overridden: com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext)
references:
- uid: f8422c74
  spec.java:
  - name: TelemetryContext
    fullName: TelemetryContext
- uid: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize*
  name: initialize
  nameWithType: DeviceInfoContextInitializer.initialize
  fullName: com.microsoft.applicationinsights.extensibility.initializer.DeviceInfoContextInitializer.initialize
  package: com.microsoft.applicationinsights.extensibility.initializer
- uid: com.microsoft.applicationinsights.extensibility.ContextInitializer
  parent: com.microsoft.applicationinsights.extensibility
  href: com.microsoft.applicationinsights.extensibility.ContextInitializer.yml
  name: ContextInitializer
  nameWithType: ContextInitializer
  fullName: com.microsoft.applicationinsights.extensibility.ContextInitializer
  type: Interface
  summary: "<p>Represents an object that implements supporting logic for TelemetryContext. <xref uid=\"\" data-throw-if-not-resolved=\"false\">com.microsoft.applicationinsights.telemetry.TelemetryContext</xref></p>"
  syntax:
    content: public interface ContextInitializer
- uid: com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext)
  parent: com.microsoft.applicationinsights.extensibility.ContextInitializer
  href: com.microsoft.applicationinsights.extensibility.ContextInitializer.yml
  name: initialize(TelemetryContext context)
  nameWithType: ContextInitializer.initialize(TelemetryContext context)
  fullName: com.microsoft.applicationinsights.extensibility.ContextInitializer.initialize(TelemetryContext context)
  type: Method
  summary: "<p>Initializes the given TelemetryContext. </p>"
  syntax:
    content: public void initialize(TelemetryContext context)
    parameters:
    - id: context
      type: f8422c74
      description: <p>A TelemetryContext to initialize. </p>
