### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  id: AzureBlobStorageHttpLogsConfig
  parent: com.microsoft.azure.management.appservice
  children:
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled()
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays()
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl()
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled(Boolean)
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer)
  - com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl(String)
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: AzureBlobStorageHttpLogsConfig
  nameWithType: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 15
  package: com.microsoft.azure.management.appservice
  summary: "<p>Http logs to azure blob storage configuration. </p>"
  syntax: &o1
    content: public class AzureBlobStorageHttpLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled()
  id: enabled()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: enabled()
  nameWithType: AzureBlobStorageHttpLogsConfig.enabled()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 82
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the enabled value.</p>\r\n<p></p>"
  syntax:
    content: public Boolean enabled()
    return:
      type: 866c2227
      description: <p>the enabled value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays()
  id: retentionInDays()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: retentionInDays()
  nameWithType: AzureBlobStorageHttpLogsConfig.retentionInDays()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 62
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public Integer retentionInDays()
    return:
      type: 08effaa0
      description: <p>the retentionInDays value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl()
  id: sasUrl()
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: sasUrl()
  nameWithType: AzureBlobStorageHttpLogsConfig.sasUrl()
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl()
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 42
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the sasUrl value.</p>\r\n<p></p>"
  syntax:
    content: public String sasUrl()
    return:
      type: "26831127"
      description: <p>the sasUrl value </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled(Boolean)
  id: withEnabled(Boolean)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: withEnabled(Boolean enabled)
  nameWithType: AzureBlobStorageHttpLogsConfig.withEnabled(Boolean enabled)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled(Boolean enabled)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 92
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the enabled value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withEnabled(Boolean enabled)
    parameters:
    - id: enabled
      type: 866c2227
      description: <p>the enabled value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
      description: <p>the AzureBlobStorageHttpLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer)
  id: withRetentionInDays(Integer)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: withRetentionInDays(Integer retentionInDays)
  nameWithType: AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays(Integer retentionInDays)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 72
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the retentionInDays value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withRetentionInDays(Integer retentionInDays)
    parameters:
    - id: retentionInDays
      type: 08effaa0
      description: <p>the retentionInDays value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
      description: <p>the AzureBlobStorageHttpLogsConfig object itself. </p>
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl(String)
  id: withSasUrl(String)
  parent: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  langs:
  - java
  name: withSasUrl(String sasUrl)
  nameWithType: AzureBlobStorageHttpLogsConfig.withSasUrl(String sasUrl)
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl(String sasUrl)
  overload: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/AzureBlobStorageHttpLogsConfig.java
    startLine: 52
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the sasUrl value.</p>\r\n<p></p>"
  syntax:
    content: public AzureBlobStorageHttpLogsConfig withSasUrl(String sasUrl)
    parameters:
    - id: sasUrl
      type: "26831127"
      description: <p>the sasUrl value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
      description: <p>the AzureBlobStorageHttpLogsConfig object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl*
  name: sasUrl
  nameWithType: AzureBlobStorageHttpLogsConfig.sasUrl
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.sasUrl
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl*
  name: withSasUrl
  nameWithType: AzureBlobStorageHttpLogsConfig.withSasUrl
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withSasUrl
  package: com.microsoft.azure.management.appservice
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays*
  name: retentionInDays
  nameWithType: AzureBlobStorageHttpLogsConfig.retentionInDays
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.retentionInDays
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays*
  name: withRetentionInDays
  nameWithType: AzureBlobStorageHttpLogsConfig.withRetentionInDays
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withRetentionInDays
  package: com.microsoft.azure.management.appservice
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled*
  name: enabled
  nameWithType: AzureBlobStorageHttpLogsConfig.enabled
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.enabled
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled*
  name: withEnabled
  nameWithType: AzureBlobStorageHttpLogsConfig.withEnabled
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.withEnabled
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig.yml
  name: AzureBlobStorageHttpLogsConfig
  nameWithType: AzureBlobStorageHttpLogsConfig
  fullName: com.microsoft.azure.management.appservice.AzureBlobStorageHttpLogsConfig
  type: Class
  summary: "<p>Http logs to azure blob storage configuration. </p>"
  syntax: *o1
