### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings
  id: WithSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSetting(String,Object)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSettings(HashMap<String, Object>)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSetting(String,Object)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSettings(HashMap<String, Object>)
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.yml
  langs:
  - java
  name: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
    startLine: 340
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage of a virtual machine scale set extension definition allowing to specify the public and private settings.</p>\r\n<p></p>"
  syntax:
    content: public interface WithSettings<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent update to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSetting(String,Object)
  id: withProtectedSetting(String,Object)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.yml
  langs:
  - java
  name: withProtectedSetting(String key, Object value)
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSetting(String key, Object value)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSetting(String key, Object value)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSetting*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
    startLine: 357
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies a private settings entry.</p>\r\n<p></p>"
  syntax:
    content: public WithAttach<ParentT> withProtectedSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a private settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the private settings entry </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttachda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSettings(HashMap<String, Object>)
  id: withProtectedSettings(HashMap<String, Object>)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.yml
  langs:
  - java
  name: withProtectedSettings(HashMap<String, Object> settings)
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSettings(HashMap<String, Object> settings)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSettings(HashMap<String, Object> settings)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
    startLine: 373
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies private settings.</p>\r\n<p></p>"
  syntax:
    content: public WithAttach<ParentT> withProtectedSettings(HashMap<String, Object> settings)
    parameters:
    - id: settings
      type: f39c727f
      description: <p>the private settings </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttachda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSetting(String,Object)
  id: withPublicSetting(String,Object)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.yml
  langs:
  - java
  name: withPublicSetting(String key, Object value)
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSetting(String key, Object value)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSetting(String key, Object value)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSetting*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
    startLine: 348
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies a public settings entry.</p>\r\n<p></p>"
  syntax:
    content: public WithAttach<ParentT> withPublicSetting(String key, Object value)
    parameters:
    - id: key
      type: "26831127"
      description: <p>the key of a public settings entry </p>
    - id: value
      type: "79317049"
      description: <p>the value of the public settings entry </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttachda8a2936
      description: <p>the next stage of the definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSettings(HashMap<String, Object>)
  id: withPublicSettings(HashMap<String, Object>)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.yml
  langs:
  - java
  name: withPublicSettings(HashMap<String, Object> settings)
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSettings(HashMap<String, Object> settings)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSettings(HashMap<String, Object> settings)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSettings*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetExtension.java
    startLine: 365
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies public settings.</p>\r\n<p></p>"
  syntax:
    content: public WithAttach<ParentT> withPublicSettings(HashMap<String, Object> settings)
    parameters:
    - id: settings
      type: f39c727f
      description: <p>the public settings </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttachda8a2936
      description: <p>the next stage of the definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: "79317049"
  spec.java:
  - name: Object
    fullName: Object
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttachda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach
    name: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach
    fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach
    href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSetting*
  name: withPublicSetting
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSetting
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSetting
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSetting*
  name: withProtectedSetting
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSetting
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSetting
  package: com.microsoft.azure.management.compute
- uid: f39c727f
  spec.java:
  - name: HashMap<String, Object>
    fullName: HashMap<String, Object>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withPublicSettings*
  name: withPublicSettings
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withPublicSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings.withProtectedSettings*
  name: withProtectedSettings
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSettings
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>.withProtectedSettings
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach.yml
  name: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach<ParentT>
  nameWithType: VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: "<p>The final stage of the virtual machine scale set extension definition. </p>"
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate,VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithAutoUpgradeMinorVersion<ParentT>,VirtualMachineScaleSetExtension.UpdateDefinitionStages.WithSettings<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent update to return to after attaching this definition </p>
