### YamlMime:ManagedReference
items:
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  id: AutoDetectSourceLanguageConfig
  parent: com.microsoft.cognitiveservices.speech
  children:
  - com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close()
  - com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages(List<String>)
  - com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange()
  - com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs(List<SourceLanguageConfig>)
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  langs:
  - java
  name: AutoDetectSourceLanguageConfig
  nameWithType: AutoDetectSourceLanguageConfig
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  type: Class
  source:
    remote: &o0
      path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
      branch: javadocs201809
      repo: https://msasg.visualstudio.com/DefaultCollection/Skyman/_git/Carbon
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
    startLine: 19
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Represents auto detect source language configuration used for specifying the possible source language candidates Updated in version 1.13.0 </p>"
  syntax: &o1
    content: public class AutoDetectSourceLanguageConfig
  inheritance:
  - java.lang.Object
  - Closeable
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close()
  id: close()
  parent: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  langs:
  - java
  name: close()
  nameWithType: AutoDetectSourceLanguageConfig.close()
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close()
  overload: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
    startLine: 101
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Explicitly frees any external resource attached to the object </p>"
  syntax:
    content: public void close()
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages(List<String>)
  id: fromLanguages(List<String>)
  parent: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  langs:
  - java
  name: fromLanguages(List<String> languages)
  nameWithType: AutoDetectSourceLanguageConfig.fromLanguages(List<String> languages)
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages(List<String> languages)
  overload: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
    startLine: 51
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Creates an instance of the AutoDetectSourceLanguageConfig </p>"
  syntax:
    content: public static AutoDetectSourceLanguageConfig fromLanguages(List<String> languages)
    parameters:
    - id: languages
      type: 7d60c20e
      description: <p>Specifies the source language candidates. This functionality was added in version 1.8.0. </p>
    return:
      type: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
      description: <p>The auto detect source language configuration being created. </p>
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange()
  id: fromOpenRange()
  parent: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  langs:
  - java
  name: fromOpenRange()
  nameWithType: AutoDetectSourceLanguageConfig.fromOpenRange()
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange()
  overload: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
    startLine: 39
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Creates an instance of the AutoDetectSourceLanguageConfig with open range Note: only <xref uid=\"com.microsoft.cognitiveservices.speech.SpeechSynthesizer\" data-throw-if-not-resolved=\"false\" data-raw-source=\"SpeechSynthesizer\"></xref> supports source language auto detection from open range, for <xref uid=\"com.microsoft.cognitiveservices.speech.Recognizer\" data-throw-if-not-resolved=\"false\" data-raw-source=\"Recognizer\"></xref>, please use AutoDetectSourceLanguageConfig with specific source languages. Added in 1.13.0 </p>"
  syntax:
    content: public static AutoDetectSourceLanguageConfig fromOpenRange()
    return:
      type: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
      description: <p>The auto detect source language configuration being created. </p>
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs(List<SourceLanguageConfig>)
  id: fromSourceLanguageConfigs(List<SourceLanguageConfig>)
  parent: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  langs:
  - java
  name: fromSourceLanguageConfigs(List<SourceLanguageConfig> sourceLanguageConfigs)
  nameWithType: AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs(List<SourceLanguageConfig> sourceLanguageConfigs)
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs(List<SourceLanguageConfig> sourceLanguageConfigs)
  overload: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs*
  type: Method
  source:
    remote: *o0
    path: source/bindings/java/com/microsoft/cognitiveservices/speech/AutoDetectSourceLanguageConfig.java
    startLine: 74
  package: com.microsoft.cognitiveservices.speech
  summary: "<p>Creates an instance of the AutoDetectSourceLanguageConfig with a list of SourceLanguageConfig </p>"
  syntax:
    content: public static AutoDetectSourceLanguageConfig fromSourceLanguageConfigs(List<SourceLanguageConfig> sourceLanguageConfigs)
    parameters:
    - id: sourceLanguageConfigs
      type: 5618da2dcom.microsoft.cognitiveservices.speech.SourceLanguageConfiga08ddfce
      description: <p>Specifies the source language config list This functionality was added in version 1.8.0. </p>
    return:
      type: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
      description: <p>The AutoDetectSourceLanguageConfig being created. </p>
references:
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange*
  name: fromOpenRange
  nameWithType: AutoDetectSourceLanguageConfig.fromOpenRange
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromOpenRange
  package: com.microsoft.cognitiveservices.speech
- uid: 7d60c20e
  spec.java:
  - name: List<String>
    fullName: List<String>
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages*
  name: fromLanguages
  nameWithType: AutoDetectSourceLanguageConfig.fromLanguages
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromLanguages
  package: com.microsoft.cognitiveservices.speech
- uid: 5618da2dcom.microsoft.cognitiveservices.speech.SourceLanguageConfiga08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.cognitiveservices.speech.SourceLanguageConfig
    name: SourceLanguageConfig
    fullName: com.microsoft.cognitiveservices.speech.SourceLanguageConfig
    href: com.microsoft.cognitiveservices.speech.SourceLanguageConfig.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs*
  name: fromSourceLanguageConfigs
  nameWithType: AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.fromSourceLanguageConfigs
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close*
  name: close
  nameWithType: AutoDetectSourceLanguageConfig.close
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.close
  package: com.microsoft.cognitiveservices.speech
- uid: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig.yml
  name: AutoDetectSourceLanguageConfig
  nameWithType: AutoDetectSourceLanguageConfig
  fullName: com.microsoft.cognitiveservices.speech.AutoDetectSourceLanguageConfig
  type: Class
  summary: "<p>Represents auto detect source language configuration used for specifying the possible source language candidates Updated in version 1.13.0 </p>"
  syntax: *o1
- uid: com.microsoft.cognitiveservices.speech.SpeechSynthesizer
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.SpeechSynthesizer.yml
  name: SpeechSynthesizer
  nameWithType: SpeechSynthesizer
  fullName: com.microsoft.cognitiveservices.speech.SpeechSynthesizer
  type: Class
  summary: "<p>Performs speech synthesis to speaker, file, or other audio output streams, and gets synthesized audio as result. Updated in version 1.14.0 </p>"
  syntax:
    content: public class SpeechSynthesizer
- uid: com.microsoft.cognitiveservices.speech.Recognizer
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.Recognizer.yml
  name: Recognizer
  nameWithType: Recognizer
  fullName: com.microsoft.cognitiveservices.speech.Recognizer
  type: Class
  summary: "<p>Defines the base class Recognizer which mainly contains common event handlers. </p>"
  syntax:
    content: public class Recognizer
- uid: com.microsoft.cognitiveservices.speech.SourceLanguageConfig
  parent: com.microsoft.cognitiveservices.speech
  href: com.microsoft.cognitiveservices.speech.SourceLanguageConfig.yml
  name: SourceLanguageConfig
  nameWithType: SourceLanguageConfig
  fullName: com.microsoft.cognitiveservices.speech.SourceLanguageConfig
  type: Class
  summary: "<p>Represents source language configuration used for specifying recognition source language Added in version 1.8.0 </p>"
  syntax:
    content: public class SourceLanguageConfig
