### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
  id: WithNewVhdDiskSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withCaching(CachingTypes)
  - com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withLun(Integer)
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 167
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage that allows configure the unmanaged disk based on new VHD.</p>\r\n<p></p>"
  syntax: &o1
    content: public interface WithNewVhdDiskSettings<ParentT> extends VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent update to return to after attaching this definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate.attach()
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withCaching(CachingTypes)
  id: withCaching(CachingTypes)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: withCaching(CachingTypes cachingType)
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withCaching*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 182
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the caching type for the unmanaged data disk.</p>\r\n<p></p>"
  syntax:
    content: public WithNewVhdDiskSettings<ParentT> withCaching(CachingTypes cachingType)
    parameters:
    - id: cachingType
      type: com.microsoft.azure.management.compute.CachingTypes
      description: "<p>the disk caching type. Possible values include: 'None', 'ReadOnly', 'ReadWrite' </p>"
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettingsda8a2936
      description: <p>the next stage of unmanaged data disk definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withLun(Integer)
  id: withLun(Integer)
  parent: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: withLun(Integer lun)
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun(Integer lun)
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun(Integer lun)
  overload: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withLun*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetUnmanagedDataDisk.java
    startLine: 174
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the logical unit number for the unmanaged data disk.</p>\r\n<p></p>"
  syntax:
    content: public WithNewVhdDiskSettings<ParentT> withLun(Integer lun)
    parameters:
    - id: lun
      type: 08effaa0
      description: <p>the logical unit number </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettingsda8a2936
      description: <p>the next stage of unmanaged data disk definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettingsda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
    name: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
    fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
    href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withLun*
  name: withLun
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.withCaching*
  name: withCaching
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate
  href: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InUpdate.yml
  name: attach()
  nameWithType: Attachable.InUpdate<ParentT>.attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InUpdate<ParentT>.attach()
  type: Method
  summary: "<p>Attaches the child definition to the parent resource update. </p>"
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: "<p>The final stage of the unmanaged data disk definition.</p>\r\n<p></p>"
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InUpdate
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent update to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinition
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinition.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinition<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinition<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinition<ParentT>
  type: Interface
  summary: "<p>The entirety of a unmanaged data disk of a virtual machine scale set definition. </p>"
  syntax:
    content: public interface UpdateDefinition<ParentT> extends VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.Blank<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithDiskSource<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>,VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent update to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings.yml
  name: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  nameWithType: VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineScaleSetUnmanagedDataDisk.UpdateDefinitionStages.WithNewVhdDiskSettings<ParentT>
  type: Interface
  summary: "<p>The stage that allows configure the unmanaged disk based on new VHD.</p>\r\n<p></p>"
  syntax: *o1
- uid: com.microsoft.azure.management.compute.CachingTypes
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.CachingTypes.yml
  name: CachingTypes
  nameWithType: CachingTypes
  fullName: com.microsoft.azure.management.compute.CachingTypes
  type: Enum
  summary: "<p>Defines values for CachingTypes. </p>"
  syntax:
    content: public enum CachingTypes
