### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.appservice.VirtualApplication
  id: VirtualApplication
  parent: com.microsoft.azure.management.appservice
  children:
  - com.microsoft.azure.management.appservice.VirtualApplication.physicalPath()
  - com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled()
  - com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories()
  - com.microsoft.azure.management.appservice.VirtualApplication.virtualPath()
  - com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath(String)
  - com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled(Boolean)
  - com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories(List<VirtualDirectory>)
  - com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath(String)
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: VirtualApplication
  nameWithType: VirtualApplication
  fullName: com.microsoft.azure.management.appservice.VirtualApplication
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 16
  package: com.microsoft.azure.management.appservice
  summary: "<p>Virtual application in an app. </p>"
  syntax: &o1
    content: public class VirtualApplication
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.appservice.VirtualApplication.physicalPath()
  id: physicalPath()
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: physicalPath()
  nameWithType: VirtualApplication.physicalPath()
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.physicalPath()
  overload: com.microsoft.azure.management.appservice.VirtualApplication.physicalPath*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 67
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the physicalPath value.</p>\r\n<p></p>"
  syntax:
    content: public String physicalPath()
    return:
      type: "26831127"
      description: <p>the physicalPath value </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled()
  id: preloadEnabled()
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: preloadEnabled()
  nameWithType: VirtualApplication.preloadEnabled()
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled()
  overload: com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 87
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the preloadEnabled value.</p>\r\n<p></p>"
  syntax:
    content: public Boolean preloadEnabled()
    return:
      type: 866c2227
      description: <p>the preloadEnabled value </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories()
  id: virtualDirectories()
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: virtualDirectories()
  nameWithType: VirtualApplication.virtualDirectories()
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories()
  overload: com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 107
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the virtualDirectories value.</p>\r\n<p></p>"
  syntax:
    content: public List<VirtualDirectory> virtualDirectories()
    return:
      type: 5618da2dcom.microsoft.azure.management.appservice.VirtualDirectorya08ddfce
      description: <p>the virtualDirectories value </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.virtualPath()
  id: virtualPath()
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: virtualPath()
  nameWithType: VirtualApplication.virtualPath()
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.virtualPath()
  overload: com.microsoft.azure.management.appservice.VirtualApplication.virtualPath*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 47
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the virtualPath value.</p>\r\n<p></p>"
  syntax:
    content: public String virtualPath()
    return:
      type: "26831127"
      description: <p>the virtualPath value </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath(String)
  id: withPhysicalPath(String)
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: withPhysicalPath(String physicalPath)
  nameWithType: VirtualApplication.withPhysicalPath(String physicalPath)
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath(String physicalPath)
  overload: com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 77
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the physicalPath value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualApplication withPhysicalPath(String physicalPath)
    parameters:
    - id: physicalPath
      type: "26831127"
      description: <p>the physicalPath value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.VirtualApplication
      description: <p>the VirtualApplication object itself. </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled(Boolean)
  id: withPreloadEnabled(Boolean)
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: withPreloadEnabled(Boolean preloadEnabled)
  nameWithType: VirtualApplication.withPreloadEnabled(Boolean preloadEnabled)
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled(Boolean preloadEnabled)
  overload: com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 97
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the preloadEnabled value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualApplication withPreloadEnabled(Boolean preloadEnabled)
    parameters:
    - id: preloadEnabled
      type: 866c2227
      description: <p>the preloadEnabled value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.VirtualApplication
      description: <p>the VirtualApplication object itself. </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories(List<VirtualDirectory>)
  id: withVirtualDirectories(List<VirtualDirectory>)
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: withVirtualDirectories(List<VirtualDirectory> virtualDirectories)
  nameWithType: VirtualApplication.withVirtualDirectories(List<VirtualDirectory> virtualDirectories)
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories(List<VirtualDirectory> virtualDirectories)
  overload: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 117
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the virtualDirectories value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualApplication withVirtualDirectories(List<VirtualDirectory> virtualDirectories)
    parameters:
    - id: virtualDirectories
      type: 5618da2dcom.microsoft.azure.management.appservice.VirtualDirectorya08ddfce
      description: <p>the virtualDirectories value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.VirtualApplication
      description: <p>the VirtualApplication object itself. </p>
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath(String)
  id: withVirtualPath(String)
  parent: com.microsoft.azure.management.appservice.VirtualApplication
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  langs:
  - java
  name: withVirtualPath(String virtualPath)
  nameWithType: VirtualApplication.withVirtualPath(String virtualPath)
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath(String virtualPath)
  overload: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/VirtualApplication.java
    startLine: 57
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the virtualPath value.</p>\r\n<p></p>"
  syntax:
    content: public VirtualApplication withVirtualPath(String virtualPath)
    parameters:
    - id: virtualPath
      type: "26831127"
      description: <p>the virtualPath value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.VirtualApplication
      description: <p>the VirtualApplication object itself. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.appservice.VirtualApplication.virtualPath*
  name: virtualPath
  nameWithType: VirtualApplication.virtualPath
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.virtualPath
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath*
  name: withVirtualPath
  nameWithType: VirtualApplication.withVirtualPath
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualPath
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualApplication.physicalPath*
  name: physicalPath
  nameWithType: VirtualApplication.physicalPath
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.physicalPath
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath*
  name: withPhysicalPath
  nameWithType: VirtualApplication.withPhysicalPath
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withPhysicalPath
  package: com.microsoft.azure.management.appservice
- uid: 866c2227
  spec.java:
  - name: Boolean
    fullName: Boolean
- uid: com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled*
  name: preloadEnabled
  nameWithType: VirtualApplication.preloadEnabled
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.preloadEnabled
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled*
  name: withPreloadEnabled
  nameWithType: VirtualApplication.withPreloadEnabled
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withPreloadEnabled
  package: com.microsoft.azure.management.appservice
- uid: 5618da2dcom.microsoft.azure.management.appservice.VirtualDirectorya08ddfce
  spec.java:
  - name: List<
    fullName: List<
  - uid: com.microsoft.azure.management.appservice.VirtualDirectory
    name: VirtualDirectory
    fullName: com.microsoft.azure.management.appservice.VirtualDirectory
    href: com.microsoft.azure.management.appservice.VirtualDirectory.yml
  - name: '>'
    fullName: '>'
- uid: com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories*
  name: virtualDirectories
  nameWithType: VirtualApplication.virtualDirectories
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.virtualDirectories
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories*
  name: withVirtualDirectories
  nameWithType: VirtualApplication.withVirtualDirectories
  fullName: com.microsoft.azure.management.appservice.VirtualApplication.withVirtualDirectories
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.VirtualDirectory
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.VirtualDirectory.yml
  name: VirtualDirectory
  nameWithType: VirtualDirectory
  fullName: com.microsoft.azure.management.appservice.VirtualDirectory
  type: Class
  summary: "<p>Directory for virtual application. </p>"
  syntax:
    content: public class VirtualDirectory
- uid: com.microsoft.azure.management.appservice.VirtualApplication
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.VirtualApplication.yml
  name: VirtualApplication
  nameWithType: VirtualApplication
  fullName: com.microsoft.azure.management.appservice.VirtualApplication
  type: Class
  summary: "<p>Virtual application in an app. </p>"
  syntax: *o1
