### YamlMime:ManagedReference
items:
- uid: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory
  id: PerformanceCountersFactory
  parent: com.microsoft.applicationinsights.extensibility
  children:
  - com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters()
  href: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.yml
  langs:
  - java
  name: PerformanceCountersFactory
  nameWithType: PerformanceCountersFactory
  fullName: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory
  type: Interface
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersFactory.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersFactory.java
    startLine: 33
  package: com.microsoft.applicationinsights.extensibility
  summary: "<p>Defines the interface that concrete factories should follow. The major method is the one that will be able create the needed Performance Counters.</p>\r\n<p>Created by gupele on 3/3/2015. </p>"
  syntax:
    content: public interface PerformanceCountersFactory
- uid: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters()
  id: getPerformanceCounters()
  parent: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory
  href: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.yml
  langs:
  - java
  name: getPerformanceCounters()
  nameWithType: PerformanceCountersFactory.getPerformanceCounters()
  fullName: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters()
  overload: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters*
  type: Method
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/extensibility/PerformanceCountersFactory.java
    startLine: 41
  package: com.microsoft.applicationinsights.extensibility
  summary: "<p>Creates the <xref uid=\"\" data-throw-if-not-resolved=\"false\">com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter</xref></p>\r\n<p>Note: The method should not throw</p>\r\n<p></p>"
  syntax:
    content: public Collection<PerformanceCounter> getPerformanceCounters()
    return:
      type: e36ca4fb
      description: <p>A collection of <xref uid="" data-throw-if-not-resolved="false">com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounter</xref></p>
references:
- uid: e36ca4fb
  spec.java:
  - name: Collection<PerformanceCounter>
    fullName: Collection<PerformanceCounter>
- uid: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters*
  name: getPerformanceCounters
  nameWithType: PerformanceCountersFactory.getPerformanceCounters
  fullName: com.microsoft.applicationinsights.extensibility.PerformanceCountersFactory.getPerformanceCounters
  package: com.microsoft.applicationinsights.extensibility
