### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  id: FileSystemApplicationLogsConfig
  parent: com.microsoft.azure.management.appservice
  children:
  - com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level()
  - com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel(LogLevel)
  href: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.yml
  langs:
  - java
  name: FileSystemApplicationLogsConfig
  nameWithType: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  type: Class
  source:
    remote: &o0
      path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemApplicationLogsConfig.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemApplicationLogsConfig.java
    startLine: 15
  package: com.microsoft.azure.management.appservice
  summary: "<p>Application logs to file system configuration. </p>"
  syntax: &o1
    content: public class FileSystemApplicationLogsConfig
  inheritance:
  - java.lang.Object
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level()
  id: level()
  parent: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.yml
  langs:
  - java
  name: level()
  nameWithType: FileSystemApplicationLogsConfig.level()
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level()
  overload: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemApplicationLogsConfig.java
    startLine: 28
  package: com.microsoft.azure.management.appservice
  summary: "<p>Get the level value.</p>\r\n<p></p>"
  syntax:
    content: public LogLevel level()
    return:
      type: com.microsoft.azure.management.appservice.LogLevel
      description: <p>the level value </p>
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel(LogLevel)
  id: withLevel(LogLevel)
  parent: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  href: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.yml
  langs:
  - java
  name: withLevel(LogLevel level)
  nameWithType: FileSystemApplicationLogsConfig.withLevel(LogLevel level)
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel(LogLevel level)
  overload: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/FileSystemApplicationLogsConfig.java
    startLine: 38
  package: com.microsoft.azure.management.appservice
  summary: "<p>Set the level value.</p>\r\n<p></p>"
  syntax:
    content: public FileSystemApplicationLogsConfig withLevel(LogLevel level)
    parameters:
    - id: level
      type: com.microsoft.azure.management.appservice.LogLevel
      description: <p>the level value to set </p>
    return:
      type: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
      description: <p>the FileSystemApplicationLogsConfig object itself. </p>
references:
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level*
  name: level
  nameWithType: FileSystemApplicationLogsConfig.level
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.level
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel*
  name: withLevel
  nameWithType: FileSystemApplicationLogsConfig.withLevel
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.withLevel
  package: com.microsoft.azure.management.appservice
- uid: com.microsoft.azure.management.appservice.LogLevel
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.LogLevel.yml
  name: LogLevel
  nameWithType: LogLevel
  fullName: com.microsoft.azure.management.appservice.LogLevel
  type: Enum
  summary: "<p>Defines values for LogLevel. </p>"
  syntax:
    content: public enum LogLevel
- uid: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  parent: com.microsoft.azure.management.appservice
  href: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig.yml
  name: FileSystemApplicationLogsConfig
  nameWithType: FileSystemApplicationLogsConfig
  fullName: com.microsoft.azure.management.appservice.FileSystemApplicationLogsConfig
  type: Class
  summary: "<p>Application logs to file system configuration. </p>"
  syntax: *o1
