### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig
  id: WithEncryptionConfig
  parent: com.microsoft.azure.management.datalakestore.v2016_11_01
  children:
  - com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig(UpdateEncryptionConfig)
  href: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.yml
  langs:
  - java
  name: DataLakeStoreAccount.UpdateStages.WithEncryptionConfig
  nameWithType: DataLakeStoreAccount.UpdateStages.WithEncryptionConfig
  fullName: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig
  type: Interface
  source:
    remote: &o0
      path: sdk/datalakestore/mgmt-v2016_11_01/src/main/java/com/microsoft/azure/management/datalakestore/v2016_11_01/DataLakeStoreAccount.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: sdk/datalakestore/mgmt-v2016_11_01/src/main/java/com/microsoft/azure/management/datalakestore/v2016_11_01/DataLakeStoreAccount.java
    startLine: 311
  package: com.microsoft.azure.management.datalakestore.v2016_11_01
  summary: "<p>The stage of the datalakestoreaccount update allowing to specify EncryptionConfig. </p>"
  syntax:
    content: public interface WithEncryptionConfig
- uid: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig(UpdateEncryptionConfig)
  id: withEncryptionConfig(UpdateEncryptionConfig)
  parent: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig
  href: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.yml
  langs:
  - java
  name: withEncryptionConfig(UpdateEncryptionConfig encryptionConfig)
  nameWithType: DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig(UpdateEncryptionConfig encryptionConfig)
  fullName: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig(UpdateEncryptionConfig encryptionConfig)
  overload: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig*
  type: Method
  source:
    remote: *o0
    path: sdk/datalakestore/mgmt-v2016_11_01/src/main/java/com/microsoft/azure/management/datalakestore/v2016_11_01/DataLakeStoreAccount.java
    startLine: 317
  package: com.microsoft.azure.management.datalakestore.v2016_11_01
  summary: "<p>Specifies encryptionConfig. </p>"
  syntax:
    content: public Update withEncryptionConfig(UpdateEncryptionConfig encryptionConfig)
    parameters:
    - id: encryptionConfig
      type: com.microsoft.azure.management.datalakestore.v2016_11_01.UpdateEncryptionConfig
      description: <p>Used for rotation of user managed Key Vault keys. Can only be used to rotate a user managed encryption Key Vault key </p>
    return:
      type: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.Update
      description: <p>the next update stage </p>
references:
- uid: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig*
  name: withEncryptionConfig
  nameWithType: DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig
  fullName: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.UpdateStages.WithEncryptionConfig.withEncryptionConfig
  package: com.microsoft.azure.management.datalakestore.v2016_11_01
- uid: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.Update
  parent: com.microsoft.azure.management.datalakestore.v2016_11_01
  href: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.Update.yml
  name: DataLakeStoreAccount.Update
  nameWithType: DataLakeStoreAccount.Update
  fullName: com.microsoft.azure.management.datalakestore.v2016_11_01.DataLakeStoreAccount.Update
  type: Interface
  summary: "<p>The template for a DataLakeStoreAccount update operation, containing all the settings that can be modified. </p>"
  syntax:
    content: public interface Update extends DataLakeStoreAccount.UpdateStages.WithDefaultGroup,DataLakeStoreAccount.UpdateStages.WithEncryptionConfig,DataLakeStoreAccount.UpdateStages.WithFirewallAllowAzureIps,DataLakeStoreAccount.UpdateStages.WithFirewallRules,DataLakeStoreAccount.UpdateStages.WithFirewallState,DataLakeStoreAccount.UpdateStages.WithNewTier,DataLakeStoreAccount.UpdateStages.WithTrustedIdProviders,DataLakeStoreAccount.UpdateStages.WithTrustedIdProviderState,DataLakeStoreAccount.UpdateStages.WithVirtualNetworkRules
- uid: com.microsoft.azure.management.datalakestore.v2016_11_01.UpdateEncryptionConfig
  parent: com.microsoft.azure.management.datalakestore.v2016_11_01
  href: com.microsoft.azure.management.datalakestore.v2016_11_01.UpdateEncryptionConfig.yml
  name: UpdateEncryptionConfig
  nameWithType: UpdateEncryptionConfig
  fullName: com.microsoft.azure.management.datalakestore.v2016_11_01.UpdateEncryptionConfig
  type: Class
  summary: "<p>The encryption configuration used to update a user managed Key Vault key. </p>"
  syntax:
    content: public class UpdateEncryptionConfig
