### YamlMime:ManagedReference
items:
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
  id: WithNewVhdDiskSettings
  parent: com.microsoft.azure.management.compute
  children:
  - com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.storeAt(String,String,String)
  - com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withCaching(CachingTypes)
  - com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withLun(Integer)
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  type: Interface
  source:
    remote: &o0
      path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineUnmanagedDataDisk.java
      branch: v1.3.0
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineUnmanagedDataDisk.java
    startLine: 142
  package: com.microsoft.azure.management.compute
  summary: "<p>The stage that allows configure the disk based on new VHD.</p>\r\n<p></p>"
  syntax: &o1
    content: public interface WithNewVhdDiskSettings<ParentT> extends VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
  inheritedMembers:
  - com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.attach()
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.storeAt(String,String,String)
  id: storeAt(String,String,String)
  parent: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: storeAt(String storageAccountName, String containerName, String vhdName)
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.storeAt(String storageAccountName, String containerName, String vhdName)
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.storeAt(String storageAccountName, String containerName, String vhdName)
  overload: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.storeAt*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineUnmanagedDataDisk.java
    startLine: 167
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies where the VHD associated with the new blank data disk needs to be stored.</p>\r\n<p></p>"
  syntax:
    content: public WithNewVhdDiskSettings<ParentT> storeAt(String storageAccountName, String containerName, String vhdName)
    parameters:
    - id: storageAccountName
      type: "26831127"
      description: <p>the storage account name </p>
    - id: containerName
      type: "26831127"
      description: <p>the name of the container to hold the new VHD file </p>
    - id: vhdName
      type: "26831127"
      description: <p>the name for the new VHD file </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettingsda8a2936
      description: <p>the next stage of data disk definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withCaching(CachingTypes)
  id: withCaching(CachingTypes)
  parent: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: withCaching(CachingTypes cachingType)
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching(CachingTypes cachingType)
  overload: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withCaching*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineUnmanagedDataDisk.java
    startLine: 157
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the caching type for the data disk.</p>\r\n<p></p>"
  syntax:
    content: public WithNewVhdDiskSettings<ParentT> withCaching(CachingTypes cachingType)
    parameters:
    - id: cachingType
      type: com.microsoft.azure.management.compute.CachingTypes
      description: "<p>the disk caching type. Possible values include: 'None', 'ReadOnly', 'ReadWrite' </p>"
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettingsda8a2936
      description: <p>the next stage of data disk definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withLun(Integer)
  id: withLun(Integer)
  parent: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  langs:
  - java
  name: withLun(Integer lun)
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun(Integer lun)
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun(Integer lun)
  overload: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withLun*
  type: Method
  source:
    remote: *o0
    path: azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineUnmanagedDataDisk.java
    startLine: 149
  package: com.microsoft.azure.management.compute
  summary: "<p>Specifies the logical unit number for the data disk.</p>\r\n<p></p>"
  syntax:
    content: public WithNewVhdDiskSettings<ParentT> withLun(Integer lun)
    parameters:
    - id: lun
      type: 08effaa0
      description: <p>the logical unit number </p>
    return:
      type: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettingsda8a2936
      description: <p>the next stage of data disk definition </p>
references:
- uid: 18a275b1
  spec.java:
  - name: ParentT
    fullName: ParentT
- uid: 08effaa0
  spec.java:
  - name: Integer
    fullName: Integer
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettingsda8a2936
  spec.java:
  - uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
    name: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
    fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
    href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  - name: <ParentT>
    fullName: <ParentT>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withLun*
  name: withLun
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withLun
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.withCaching*
  name: withCaching
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.withCaching
  package: com.microsoft.azure.management.compute
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.storeAt*
  name: storeAt
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.storeAt
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>.storeAt
  package: com.microsoft.azure.management.compute
- uid: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.attach()
  parent: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition
  href: com.microsoft.azure.management.resources.fluentcore.model.Attachable.InDefinition.yml
  name: attach()
  nameWithType: Attachable.InDefinition<ParentT>.attach()
  fullName: ParentT com.microsoft.azure.management.resources.fluentcore.model.Attachable<ParentT>.InDefinition<ParentT>.attach()
  type: Method
  summary: "<p>Attaches the child definition to the parent resource definiton. </p>"
  syntax:
    content: public ParentT attach()
    return:
      type: 18a275b1
      description: <p>the next stage of the parent definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach.yml
  name: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
  type: Interface
  summary: "<p>The final stage of the data disk definition.</p>\r\n<p></p>"
  syntax:
    content: public interface WithAttach<ParentT> extends Attachable<ParentT>.InDefinition
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionWithNewVhd
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionWithNewVhd.yml
  name: VirtualMachineUnmanagedDataDisk.DefinitionWithNewVhd<ParentT>
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionWithNewVhd<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionWithNewVhd<ParentT>
  type: Interface
  summary: "<p>The entirety of a unmanaged data disk of a virtual machine scale set definition. </p>"
  syntax:
    content: public interface DefinitionWithNewVhd<ParentT> extends VirtualMachineUnmanagedDataDisk.DefinitionStages.Blank<ParentT>,VirtualMachineUnmanagedDataDisk.DefinitionStages.WithDiskSource<ParentT>,VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>,VirtualMachineUnmanagedDataDisk.DefinitionStages.WithAttach<ParentT>
    typeParameters:
    - id: ParentT
      type: 18a275b1
      description: <p>the stage of the parent definition to return to after attaching this definition </p>
- uid: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings.yml
  name: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  nameWithType: VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  fullName: com.microsoft.azure.management.compute.VirtualMachineUnmanagedDataDisk.DefinitionStages.WithNewVhdDiskSettings<ParentT>
  type: Interface
  summary: "<p>The stage that allows configure the disk based on new VHD.</p>\r\n<p></p>"
  syntax: *o1
- uid: com.microsoft.azure.management.compute.CachingTypes
  parent: com.microsoft.azure.management.compute
  href: com.microsoft.azure.management.compute.CachingTypes.yml
  name: CachingTypes
  nameWithType: CachingTypes
  fullName: com.microsoft.azure.management.compute.CachingTypes
  type: Enum
  summary: "<p>Defines values for CachingTypes. </p>"
  syntax:
    content: public enum CachingTypes
