### YamlMime:ManagedReference
items:
- uid: system.fabric.description.ConfigurationProperty
  id: ConfigurationProperty
  parent: system.fabric.description
  children:
  - system.fabric.description.ConfigurationProperty.getName()
  - system.fabric.description.ConfigurationProperty.getValue()
  - system.fabric.description.ConfigurationProperty.isEncrypted()
  - system.fabric.description.ConfigurationProperty.isMustOverride()
  href: system.fabric.description.ConfigurationProperty.yml
  langs:
  - java
  name: ConfigurationProperty
  nameWithType: ConfigurationProperty
  fullName: system.fabric.description.ConfigurationProperty
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
    startLine: 3
  package: system.fabric.description
  summary: "<p>Specifies a name-value pair that is used to configure a service or application. </p>"
  syntax:
    content: public class ConfigurationProperty
  inheritance:
  - java.lang.Object
- uid: system.fabric.description.ConfigurationProperty.getName()
  id: getName()
  parent: system.fabric.description.ConfigurationProperty
  href: system.fabric.description.ConfigurationProperty.yml
  langs:
  - java
  name: getName()
  nameWithType: ConfigurationProperty.getName()
  fullName: system.fabric.description.ConfigurationProperty.getName()
  overload: system.fabric.description.ConfigurationProperty.getName*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
    startLine: 22
  package: system.fabric.description
  summary: "<p>Specifies the name of the setting.</p>\r\n<p></p>"
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>The name of the setting. </p>
- uid: system.fabric.description.ConfigurationProperty.getValue()
  id: getValue()
  parent: system.fabric.description.ConfigurationProperty
  href: system.fabric.description.ConfigurationProperty.yml
  langs:
  - java
  name: getValue()
  nameWithType: ConfigurationProperty.getValue()
  fullName: system.fabric.description.ConfigurationProperty.getValue()
  overload: system.fabric.description.ConfigurationProperty.getValue*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
    startLine: 31
  package: system.fabric.description
  summary: "<p>Gets the value of the setting.</p>\r\n<p></p>"
  syntax:
    content: public String getValue()
    return:
      type: "26831127"
      description: <p>The value of the setting. </p>
- uid: system.fabric.description.ConfigurationProperty.isEncrypted()
  id: isEncrypted()
  parent: system.fabric.description.ConfigurationProperty
  href: system.fabric.description.ConfigurationProperty.yml
  langs:
  - java
  name: isEncrypted()
  nameWithType: ConfigurationProperty.isEncrypted()
  fullName: system.fabric.description.ConfigurationProperty.isEncrypted()
  overload: system.fabric.description.ConfigurationProperty.isEncrypted*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
    startLine: 49
  package: system.fabric.description
  summary: "<p>Specifies whether the configuration is encrypted.</p>\r\n<p></p>"
  syntax:
    content: public boolean isEncrypted()
    return:
      type: 4fc6e284
      description: <p>Returns true if the configuration is encrypted; false, otherwise. </p>
- uid: system.fabric.description.ConfigurationProperty.isMustOverride()
  id: isMustOverride()
  parent: system.fabric.description.ConfigurationProperty
  href: system.fabric.description.ConfigurationProperty.yml
  langs:
  - java
  name: isMustOverride()
  nameWithType: ConfigurationProperty.isMustOverride()
  fullName: system.fabric.description.ConfigurationProperty.isMustOverride()
  overload: system.fabric.description.ConfigurationProperty.isMustOverride*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationProperty.java
    startLine: 40
  package: system.fabric.description
  summary: "<p>Gets a flag indicating whether the setting must be overridden in the application manifest.</p>\r\n<p></p>"
  syntax:
    content: public boolean isMustOverride()
    return:
      type: 4fc6e284
      description: <p>Flag indicating whether the setting must be overridden in the application manifest. </p>
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: system.fabric.description.ConfigurationProperty.getName*
  name: getName
  nameWithType: ConfigurationProperty.getName
  fullName: system.fabric.description.ConfigurationProperty.getName
  package: system.fabric.description
- uid: system.fabric.description.ConfigurationProperty.getValue*
  name: getValue
  nameWithType: ConfigurationProperty.getValue
  fullName: system.fabric.description.ConfigurationProperty.getValue
  package: system.fabric.description
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: system.fabric.description.ConfigurationProperty.isMustOverride*
  name: isMustOverride
  nameWithType: ConfigurationProperty.isMustOverride
  fullName: system.fabric.description.ConfigurationProperty.isMustOverride
  package: system.fabric.description
- uid: system.fabric.description.ConfigurationProperty.isEncrypted*
  name: isEncrypted
  nameWithType: ConfigurationProperty.isEncrypted
  fullName: system.fabric.description.ConfigurationProperty.isEncrypted
  package: system.fabric.description
