### YamlMime:ManagedReference
items:
- uid: system.fabric.description.ConfigurationSettings
  id: ConfigurationSettings
  parent: system.fabric.description
  children:
  - system.fabric.description.ConfigurationSettings.getSections()
  href: system.fabric.description.ConfigurationSettings.yml
  langs:
  - java
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: system.fabric.description.ConfigurationSettings
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationSettings.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationSettings.java
    startLine: 7
  package: system.fabric.description
  summary: "<p>Describes the configuration settings. </p>"
  syntax:
    content: public class ConfigurationSettings
  inheritance:
  - java.lang.Object
- uid: system.fabric.description.ConfigurationSettings.getSections()
  id: getSections()
  parent: system.fabric.description.ConfigurationSettings
  href: system.fabric.description.ConfigurationSettings.yml
  langs:
  - java
  name: getSections()
  nameWithType: ConfigurationSettings.getSections()
  fullName: system.fabric.description.ConfigurationSettings.getSections()
  overload: system.fabric.description.ConfigurationSettings.getSections*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationSettings.java
    startLine: 25
  package: system.fabric.description
  summary: "<p>Gets the name/value pair collection of the sections.</p>\r\n<p></p>"
  syntax:
    content: public HashMap<String, ConfigurationSection> getSections()
    return:
      type: 292b5718system.fabric.description.ConfigurationSectiona08ddfce
      description: <p>the name/value pair collection of the sections. </p>
references:
- uid: 292b5718system.fabric.description.ConfigurationSectiona08ddfce
  spec.java:
  - name: 'HashMap<String, '
    fullName: 'HashMap<String, '
  - uid: system.fabric.description.ConfigurationSection
    name: ConfigurationSection
    fullName: system.fabric.description.ConfigurationSection
    href: system.fabric.description.ConfigurationSection.yml
  - name: '>'
    fullName: '>'
- uid: system.fabric.description.ConfigurationSettings.getSections*
  name: getSections
  nameWithType: ConfigurationSettings.getSections
  fullName: system.fabric.description.ConfigurationSettings.getSections
  package: system.fabric.description
- uid: system.fabric.description.ConfigurationSection
  parent: system.fabric.description
  href: system.fabric.description.ConfigurationSection.yml
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: system.fabric.description.ConfigurationSection
  type: Class
  summary: "<p>Defines any configuration that can be written and read from a configuration store </p>"
  syntax:
    content: public class ConfigurationSection
