### YamlMime:ManagedReference
items:
- uid: system.fabric.description.ConfigurationPackageDescription
  id: ConfigurationPackageDescription
  parent: system.fabric.description
  href: system.fabric.description.ConfigurationPackageDescription.yml
  langs:
  - java
  name: ConfigurationPackageDescription
  nameWithType: ConfigurationPackageDescription
  fullName: system.fabric.description.ConfigurationPackageDescription
  type: Class
  source:
    remote:
      path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationPackageDescription.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/description/ConfigurationPackageDescription.java
    startLine: 3
  package: system.fabric.description
  summary: "<p>Describes a configuration package. </p>"
  syntax:
    content: public class ConfigurationPackageDescription extends PackageDescription
  inheritance:
  - java.lang.Object
  - system.fabric.description.PackageDescription
  inheritedMembers:
  - system.fabric.description.PackageDescription.getName()
  - system.fabric.description.PackageDescription.getServiceManifestName()
  - system.fabric.description.PackageDescription.getServiceManifestVersion()
  - system.fabric.description.PackageDescription.getVersion()
  - system.fabric.description.PackageDescription.PackageDescription(String,String,String,String)
references:
- uid: system.fabric.description.PackageDescription.getName()
  parent: system.fabric.description.PackageDescription
  href: system.fabric.description.PackageDescription.yml
  name: getName()
  nameWithType: PackageDescription.getName()
  fullName: system.fabric.description.PackageDescription.getName()
  type: Method
  summary: "<p>Specifies the name of the package.</p>\r\n<p></p>"
  syntax:
    content: public String getName()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric.description.PackageDescription.getServiceManifestName()
  parent: system.fabric.description.PackageDescription
  href: system.fabric.description.PackageDescription.yml
  name: getServiceManifestName()
  nameWithType: PackageDescription.getServiceManifestName()
  fullName: system.fabric.description.PackageDescription.getServiceManifestName()
  type: Method
  summary: "<p>Specifies the name of the service manifest.</p>\r\n<p></p>"
  syntax:
    content: public String getServiceManifestName()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric.description.PackageDescription.getServiceManifestVersion()
  parent: system.fabric.description.PackageDescription
  href: system.fabric.description.PackageDescription.yml
  name: getServiceManifestVersion()
  nameWithType: PackageDescription.getServiceManifestVersion()
  fullName: system.fabric.description.PackageDescription.getServiceManifestVersion()
  type: Method
  summary: "<p>Specifies the path to the package.</p>\r\n<p></p>"
  syntax:
    content: public String getServiceManifestVersion()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric.description.PackageDescription.getVersion()
  parent: system.fabric.description.PackageDescription
  href: system.fabric.description.PackageDescription.yml
  name: getVersion()
  nameWithType: PackageDescription.getVersion()
  fullName: system.fabric.description.PackageDescription.getVersion()
  type: Method
  summary: "<p>Specifies the version of the package.</p>\r\n<p></p>"
  syntax:
    content: public String getVersion()
    return:
      type: "26831127"
      description: <p>Returns String. </p>
- uid: system.fabric.description.PackageDescription.PackageDescription(String,String,String,String)
  parent: system.fabric.description.PackageDescription
  href: system.fabric.description.PackageDescription.yml
  name: PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
  nameWithType: PackageDescription.PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
  fullName: system.fabric.description.PackageDescription.PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
  type: Constructor
  syntax:
    content: public PackageDescription(String name, String version, String serviceManifestName, String serviceManifestVersion)
    parameters:
    - id: name
      type: "26831127"
    - id: version
      type: "26831127"
    - id: serviceManifestName
      type: "26831127"
    - id: serviceManifestVersion
      type: "26831127"
- uid: system.fabric.description.PackageDescription
  parent: system.fabric.description
  href: system.fabric.description.PackageDescription.yml
  name: PackageDescription
  nameWithType: PackageDescription
  fullName: system.fabric.description.PackageDescription
  type: Class
  summary: "<p>Represents a base class for all package descriptions.</p>\r\n<p></p>"
  syntax:
    content: public class PackageDescription
